export const GET_TOPSTORIE_LIST_SCIENCE = "GET_TOPSTORIE_LIST_SCIENCE";
export const SET_TOPSTORIE_LIST_SCIENCE = "SET_TOPSTORIE_LIST_SCIENCE";
export const GET_DOG_BREED_BY_NAME = "GET_DOG_BREED_BY_NAME";
export const SET_DOG_BREED_BY_NAME_IMAGE_LIST = "SET_DOG_BREED_BY_NAME_IMAGE_LIST";