export const GET_DOG_LIST = "GET_DOG_LIST";
export const SET_DOG_LIST = "SET_DOG_LIST";
export const GET_DOG_BREED_BY_NAME = "GET_DOG_BREED_BY_NAME";
export const SET_DOG_BREED_BY_NAME_IMAGE_LIST = "SET_DOG_BREED_BY_NAME_IMAGE_LIST";